
export const SET_FORM_NAME = "SET_FORM_NAME";
export const SET_FORM_EMAIL = "SET_FORM_EMAIL";
export const SET_FORM_MESSAGE = "SET_FORM_MESSAGE";
export const SUBMIT_CONTACT_FORM = "SUBMIT_CONTACT_FORM";
export const SET_FORM_SUBMIT_SUCCESS = "SET_FORM_SUBMIT_SUCCESS";
export const SET_FORM_ERROR_MESSAGE = "SET_FORM_ERROR_MESSAGE";


export const SET_CHAT_EXPANDED = "SET_CHAT_EXPANDED";
export const SET_CHAT_MESSAGES = "SET_CHAT_MESSAGES";
export const SEND_CHAT_MESSAGE = "SEND_CHAT_MESSAGE";
export const ASSISTANT_REPLY_SUCCESS = "ASSISTANT_REPLY_SUCCESS";
export const SET_CHAT_INPUT = "SET_CHAT_INPUT";
export const SET_CHAT_HAS_SCROLLED_PAGE = "SET_CHAT_HAS_SCROLLED_PAGE";



