
export const SET_FORM_NAME = "SET_FORM_NAME";
export const SET_FORM_EMAIL = "SET_FORM_EMAIL";
export const SET_FORM_MESSAGE = "SET_FORM_MESSAGE";
export const SUBMIT_CONTACT_FORM = "SUBMIT_CONTACT_FORM";
export const SET_FORM_SUBMIT_SUCCESS = "SET_FORM_SUBMIT_SUCCESS";
export const SET_FORM_ERROR_MESSAGE = "SET_FORM_ERROR_MESSAGE";


