version: "3.9"

services:
  backend:
    build:
      context: ./email
    container_name: fastapi-backend
    environment:
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./portefolio-front
    container_name: react-frontend
    ports:
      - "8083:80"
    environment:
      - REACT_APP_API_HOST=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
