name: Deploy Portfolio to Docker

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image locally
        run: |
          docker build -t portfolio:latest .

      - name: Stop existing container (if running)
        run: |
          docker rm -f react-app || true

      - name: Run Docker container
        run: |
          docker run -d --name react-app -p 8083:80 portfolio:latest
